# Generated by Django 4.2.6 on 2023-10-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_post_app', '0002_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
