# Generated by Django 4.2.6 on 2023-10-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_post_app', '0003_detail_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='create',
        ),
        migrations.AddField(
            model_name='detail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
