# Generated by Django 4.2.6 on 2023-10-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_post_app', '0005_remove_detail_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
